spring.application.name=DeliveryFoodApp
spring.profiles.active=dev
#spring.jackson.property-naming-strategy=SNAKE_CASE
restaurants.file=data/restaurants.json
dishes.file=data/dishes.json

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui
springdoc.swagger-ui.operationsSorter=method
